import numpy as np
import healpy as hp
import matplotlib.pyplot as plt

mfi_l,mfi_111,mfi_113,mfi_217,mfi_219,mfi_311,mfi_313,mfi_417,mfi_419 = np.loadtxt('/Users/mpeel/Documents/QUIJOTE/MFI/quijote_mfi_wfs.dat',unpack=True)
# print(mfi_l,mfi_111)
# exit()
# mfi_111 = np.sqrt(mfi_111)
# mfi_113 = np.sqrt(mfi_113)
# mfi_217 = np.sqrt(mfi_217)
# mfi_219 = np.sqrt(mfi_219)
# mfi_311 = np.sqrt(mfi_311)
# mfi_313 = np.sqrt(mfi_313)
# mfi_417 = np.sqrt(mfi_417)
# mfi_419 = np.sqrt(mfi_419)

wmap_l,wmap_k,wmap_kerr = np.loadtxt('/Users/mpeel/Documents/WMAP/wmap_ampl_bl_9yr_v5p1/wmap_ampl_bl_K1_9yr_v5p1.txt',unpack=True)
wmap_l,wmap_ka,wmap_kaerr = np.loadtxt('/Users/mpeel/Documents/WMAP/wmap_ampl_bl_9yr_v5p1/wmap_ampl_bl_Ka1_9yr_v5p1.txt',unpack=True)
# print(wmap_k)
wmap_k = wmap_k**2
wmap_ka = wmap_ka**2

nside = 512
conv_windowfunction = hp.gauss_beam(np.radians(60.0/60.0),3*nside)**2
conv_windowfunction2 = hp.gauss_beam(np.radians(50.0/60.0),3*nside)**2
conv_windowfunction3 = hp.gauss_beam(np.radians(70.0/60.0),3*nside)**2
pixelwin = hp.sphtfunc.pixwin(512,pol=False,lmax=3*nside)
plt.plot(conv_windowfunction,ls='dashed',label='60')
plt.plot(conv_windowfunction2,ls='dashed',label='50')
plt.plot(conv_windowfunction3,ls='dashed',label='70')
plt.plot(mfi_111,label='MFI_111')
plt.plot(mfi_113,label='MFI_113')
plt.plot(mfi_217,label='MFI_217')
plt.plot(mfi_219,label='MFI_219')
plt.plot(mfi_311,label='MFI_311')
plt.plot(mfi_313,label='MFI_313')
plt.plot(mfi_417,label='MFI_417')
plt.plot(mfi_419,label='MFI_419')
plt.plot(wmap_k,label='WMAP_K')
plt.plot(wmap_ka,label='WMAP_Ka')
# plt.plot(pixelwin,label='pixel')
l = plt.legend(prop={'size':6})
l.set_zorder(20)
plt.yscale('log')
plt.savefig('beams_plot1.pdf')
plt.xlim((0,600))
plt.ylim((1e-6,1e-0))
plt.savefig('beams_plot1_zoom.pdf')
plt.xlim((0,100))
plt.ylim((5e-1,1e-0))
plt.savefig('beams_plot1_zoom2.pdf')
plt.clf()

# plt.plot(conv_windowfunction/conv_windowfunction2,label='50_60')
# plt.plot(pixelwin*conv_windowfunction/conv_windowfunction2,label='pix')
# l = plt.legend(prop={'size':6})
# l.set_zorder(20)
# plt.yscale('log')
# plt.savefig('beams_plot2.pdf')
# plt.clf()

conv_windowfunction = conv_windowfunction[0:len(mfi_111)]

plt.plot(conv_windowfunction/mfi_111,label='MFI_111')
plt.plot(conv_windowfunction/mfi_113,label='MFI_113')
plt.plot(conv_windowfunction/mfi_217,label='MFI_217')
plt.plot(conv_windowfunction/mfi_219,label='MFI_219')
plt.plot(conv_windowfunction/mfi_311,label='MFI_311')
plt.plot(conv_windowfunction/mfi_313,label='MFI_313')
plt.plot(conv_windowfunction/mfi_417,label='MFI_417')
plt.plot(conv_windowfunction/mfi_419,label='MFI_419')
plt.plot(conv_windowfunction[0:len(wmap_k)]/wmap_k,label='WMAP_K')
plt.plot(conv_windowfunction[0:len(wmap_ka)]/wmap_ka,label='WMAP_Ka')
plt.xlabel('Multipole')
plt.ylabel('Convolving window function')
l = plt.legend(prop={'size':6})
l.set_zorder(20)
plt.savefig('beams_convolve.pdf')
plt.xlim(0,600)
plt.ylim(0.0,1.5)
plt.savefig('beams_convolve_zoom.pdf')
plt.clf()

plt.plot(np.sqrt(conv_windowfunction/mfi_111),label='MFI_111')
plt.plot(np.sqrt(conv_windowfunction/mfi_113),label='MFI_113')
plt.plot(np.sqrt(conv_windowfunction/mfi_217),label='MFI_217')
plt.plot(np.sqrt(conv_windowfunction/mfi_219),label='MFI_219')
plt.plot(np.sqrt(conv_windowfunction/mfi_311),label='MFI_311')
plt.plot(np.sqrt(conv_windowfunction/mfi_313),label='MFI_313')
plt.plot(np.sqrt(conv_windowfunction/mfi_417),label='MFI_417')
plt.plot(np.sqrt(conv_windowfunction/mfi_419),label='MFI_419')
plt.plot(np.sqrt(conv_windowfunction[0:len(wmap_k)]/wmap_k),label='WMAP_K')
plt.plot(np.sqrt(conv_windowfunction[0:len(wmap_ka)]/wmap_ka),label='WMAP_Ka')
plt.xlabel('Multipole')
plt.ylabel('Convolving beam function')
l = plt.legend(prop={'size':6})
l.set_zorder(20)
plt.savefig('beams_convolve_beam.pdf')
plt.xlim(0,600)
plt.ylim(0.0,1.5)
plt.savefig('beams_convolve_beam_zoom.pdf')
